vision:
  surface_frame_name: id_0

initialization:
  initial_pose_offset: [0.25, 0.0, 0.35] # w.r.t the surface_frame_name
  initial_approach_angle: 2.0 # in radians
  actionlib_server_names:
    manipulation_action_name: /realtime_loop/dexterous_manipulation
    approach_action_name: /realtime_loop/approach_controller
    move_action_name: /realtime_loop/move_controller
    client_action_name: manipulation_client
  controller_names:
    move_controller: move_joint_controller
    approach_controller: approach_joint_controller
    manipulation_controller: manipulation_joint_controller
  controller_timeouts:
    move_timeout: 30
    approach_timeout: 20
    manipulation_timeout: 2000
  gravity_compensation_service_name: /gravity_compensation/calibrate_bias
  server_timeout: 2
  exclude_controller_names: [l_gripper_controller]

experiment:
  feedback_rate: 1
  tool_frame_name: l_gripper_tool_frame
  base_link_name: torso_lift_link
  num_of_experiments: 1
  use_vision: true
  sim_mode: false
  approach_velocity: -0.03
  approach_force: 0.15
  goal_theta: 0.15
  goal_x: 0.2
  goal_force: 0.6
