# empty goal to trigger controller
---
time elapsed_time
---
float64[] commanded_effort # Values sent to the robot
float64[] position_error
float64[] velocity_error
float64 position_error_norm
float64 velocity_error_norm
