sensor_msgs/JointState commanded_joint_state  # Taken as input. Uses the position and velocity fields as references, referenced by name
bool use_current_position # Ignores the position field of the commanded_joint_state and uses the current values instead
---
float64[] commanded_effort # Values sent to the robot
float64[] position_error
float64[] velocity_error
float64 position_error_norm
float64 velocity_error_norm
---
time elapsed_time
