common:
  base_link_name: torso_lift_link
  end_effector_link_name: l_wrist_roll_link
  force_torque_frame: l_gripper_tool_frame
  wdls_epsilon: 0.0001
  feedback_rate: 50
  force_torque_topic: /ft_sensor/ft_compensated

manipulation_controller:
  action_server_name: dexterous_manipulation
  spring_constant: 0.3
  gains:
    k_1: 0.0
    k_2: -0.0
    k_3: 0.0
  rotational_gains: [5, 0, 5] #[5, 0, 5] # These should be IN THE SURFACE FRAME
  estimate_length: true
  hardcoded_length: 0.11 # from the gripper tool frame to the part tip
  initial_angle_offset: 1.2

approach_controller:
  action_server_name: approach_controller
  rotational_gains: [5, 5, 5]

move_controller:
  action_server_name: move_controller
  max_allowed_error: 0.5
  velocity_gain: 1.0
  error_threshold: 0.05
  ik_service_name: /pr2_left_arm_kinematics/get_ik
  ik_info_service_name: /pr2_left_arm_kinematics/get_ik_solver_info
