# Goal: triggers the controller.
int32 arm
geometry_msgs/TwistStamped approach_command
float64 contact_force

int32 LEFT_ARM = 0
int32 RIGHT_ARM = 1
---
# Result:

---
# Feedback: information that may be used to debug the controller
geometry_msgs/WrenchStamped current_wrench
float64 approach_direction_force
float64[] velocity_reference
geometry_msgs/TwistStamped commanded_twist
geometry_msgs/TwistStamped error_twist
