# Goal: triggers the controller.
geometry_msgs/PoseStamped surface_frame
geometry_msgs/PoseStamped goal_pose
---
# Result:
---
# Feedback: information that may be used to debug the controller
float64 desired_orientation
float64 estimated_orientation
