# Goal: triggers the controller.
geometry_msgs/PoseStamped surface_frame
float64 x_d # defined along the surface frame x axis
float64 theta_d # defined around the surface frame y axis
float64 desired_contact_force

bool is_debug
bool use_debug_eef_to_grasp
bool use_surface_rotation_axis
geometry_msgs/Vector3 debug_eef_to_grasp
geometry_msgs/Twist debug_twist
---
# Result:
---
# Feedback: information that may be used to debug the controller
float64 x_c_hat
float64 x_d
float64 theta_c_hat
float64 theta_d
float64 f_c_hat # estimated
float64 f_c # computed from f_e
float64 f_d
float64 k_s # estimated
float64 torque_c
float64 error_x
float64 error_theta
float64 error_force
float64 spring_angle
float64 eef_angle
float64 commanded_x
float64 commanded_y
float64 commanded_rot
geometry_msgs/Point f_e
geometry_msgs/Point tau_e
geometry_msgs/Point rot_gains
geometry_msgs/Twist commanded_twist
geometry_msgs/Twist corrected_twist
