# Goal: triggers the controller.
int32 rod_arm
int32 surface_arm
float64 goal_force
float64 vd_amplitude
float64 vd_frequency
float64 wd_amplitude
float64 wd_frequency
float64 nullspace_gain
bool use_nullspace
bool use_estimates

int32 LEFT_ARM = 0
int32 RIGHT_ARM = 1
---
# Result:

---
# Feedback: information that may be used to debug the controller
geometry_msgs/TwistStamped relative_twist
geometry_msgs/TwistStamped absolute_twist
geometry_msgs/TwistStamped controller_output
geometry_msgs/Vector3 r1
geometry_msgs/Vector3 r2
geometry_msgs/Vector3 p1
geometry_msgs/Vector3 p2
geometry_msgs/Vector3 pc
geometry_msgs/WrenchStamped surface_wrench
float64 task_compatibility
float64 alpha