# Goal: triggers the controller.
geometry_msgs/PoseStamped desired_pose
---
# Result:

---
# Feedback: information that may be used to debug the controller
float64[] joint_position_references
float64[] joint_position_errors
float64[] joint_velocity_references
float64[] joint_velocity_errors
