# Empty goal
bool use_goal # if false, will keep current values
geometry_msgs/Vector3 initial_pose_offset # w.r.t camera frame
float64 initial_approach_angle
float64 manipulation_timeout
int32 num_of_experiments
std_msgs/String bag_prefix
geometry_msgs/Vector3 desired_state
bool randomize_desired_state
geometry_msgs/Vector3 randomization_covars

---
# Empty result
---
# Provide status of what's being run as feedback
string current_action
