# Empty goal
bool use_goal # if false, will keep current values
bool scale_alpha
bool use_estimates
bool use_nullspace
int32 rod_arm
int32 surface_arm
float64 goal_force
float64 nullspace_gain
float64 init_t_error
float64 init_k_error
float64 mechanism_timeout
int32 num_of_experiments
std_msgs/String bag_prefix
float64 vd_amp
float64 wd_amp
float64 vd_freq
float64 wd_freq
bool randomize_initial_error
float64 t_min
float64 t_max
float64 k_min
float64 k_max

int32 LEFT = 0
int32 RIGHT = 1
---
# Empty result
---
# Provide status of what's being run as feedback
string current_action
string progress
