manipulation_controller:
  action_server_name: dexterous_manipulation
  end_effector_link_name: eef_name
  base_link_name: pr2_base_name
  wdls_epsilon: 0.01

  spring_constant: 2

  gains:
    k_1: 1
    k_2: 1
    k_3: 1
